[package]
name = "wfmpsc"
version = "0.1.0"
license = "MPL-2.0"
repository = "https://foss.alic.dev/dist1ll/wfmpsc"
description = "Wait-free, cache-aware MPSC queue for serial output"
autotests = false
edition = "2021"

[dependencies]
paste = "1.0.9"

[lib]
doctest = false

[[bin]]
name = "main"
doctest = false

[[bench]]
name = "alignment"
