[env]
WFMPSC_BENCH_QUEUE_SIZE = { value = "16", force = false }
WFMPSC_BENCH_PRODUCER_COUNT = { value = "9", force = false }
WFMPSC_BENCH_DUMMY_INSTRUCTIONS = { value = "0", force = false }
WFMPSC_BENCH_CHUNK_SIZE = { value = "2", force = false }
